import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Sosial | Profile",
  description: "Generated by create next app",
};

const Page = () => {
  return (
    <div>Page</div>
  )
}

export default Page