import CenterMenu from "@/components/CenterMenu";
import AddPost from "@/components/CenterMenu/AddPost";
import Feed from "@/components/CenterMenu/Feed";
import Stories from "@/components/CenterMenu/Stories";
import LeftMenu from "@/components/LeftMenu";
import RightMenu from "@/components/RightMenu";
import { Metadata } from "next";
//! Change the metadata

export const metadata: Metadata = {
  title: "Sosial",
  description: "Generated by create next app",
};
const Page = () => {
  return (
    <main className="flex gap-6 pt-6">
      <div className="hidden xl:block w-[20%]">
        <LeftMenu type="home" />
      </div>
      <div className="w-full lg:w-[70%] xl:w-[50%]">
        <div className="flex flex-col gap-6">
          <Stories />
          <AddPost />
          <Feed tipe="home" />
        </div>
        {/* <CenterMenu /> */}
      </div>
      <div className="hidden lg:block w-[30%]">
        <RightMenu />
      </div>
    </main>
  );
};

export default Page;
