import Feed from "@/components/CenterMenu/Feed";
import LeftMenu from "@/components/LeftMenu";
import RightMenu from "@/components/RightMenu";
import prisma from "@/libs/prisma";
import { auth } from "@clerk/nextjs/server";
import { User } from "@prisma/client";
import { Metadata } from "next";
import Image from "next/image";
import { notFound } from "next/navigation";
import { CgProfile } from "react-icons/cg";

export const metadata: Metadata = {
  title: "Sosial | Profile",
  description: "Generated by create next app",
};

const Page = async ({ params }: { params: { username: string } }) => {
  const { username } = await params;

  const user: User | null | any = await prisma.user.findFirst({
    where: { username },
    include: {
      followers: true,
      followings: true,
      _count: {
        select: {
          posts: true,
          followers: true,
          followings: true,
        },
      },
      posts: {
        include: {
          comments: true,
        },
      },
    },
  });

  if (!user) return notFound();

  const { userId: currentUser } = await auth();

  let isBlocked;

  if (currentUser) {
    const res = await prisma.block.findFirst({
      where: {
        blockerId: currentUser,
        blockedId: user.id,
      },
    });
    if (res) {
      isBlocked = true;
    } else {
      isBlocked = false;
    }
  }

  if (isBlocked) return notFound();

  return (
    <main className="flex gap-6 pt-6">
      <div className="hidden xl:block w-[20%]">
        <LeftMenu type="profile" />
      </div>
      <div className="w-full lg:w-[70%] xl:w-[50%]">
        <div className="flex flex-col gap-6">
          <div className="flex flex-col justify-center items-center bg-zinc-950 shadow-md shadow-zinc-600 p-4 rounded-xl">
            <div className="w-full h-64 relative">
              <Image
                src={user?.cover!}
                alt="..."
                fill
                className="object-cover rounded-lg"
              />
              {user?.avatar ? (
                <Image
                  src={user.avatar}
                  alt="..."
                  width={128}
                  height={128}
                  className="h-32 w-32 rounded-full absolute right-0 left-0 bg-black m-auto -bottom-16 ring-4 ring-white"
                />
              ) : (
                <CgProfile className="h-32 w-32 rounded-full absolute right-0 left-0 bg-black m-auto -bottom-16 ring-4 ring-white" />
              )}
            </div>
            <h1 className="mt-20 mb-4 text-2xl font-semibold">
              {user?.username}
            </h1>
            <div className="flex justify-center items-center gap-12 mb-4 text-sm font-medium">
              <div className="flex flex-col items-center">
                <span>{user!._count!.posts!}</span>
                <span>Post</span>
              </div>
              <div className="flex flex-col items-center">
                <span>{user!._count!.followers!}</span>
                <span>Followers</span>
              </div>
              <div className="flex flex-col items-center">
                <span>{user!._count!.followings}</span>
                <span>Following</span>
              </div>
            </div>
          </div>
          <div className="mt-10">
            <Feed tipe="profile" userId={user.id} />
          </div>
        </div>
      </div>
      <div className="hidden lg:block w-[30%]">
        <RightMenu userId={user?.id} user={user} />
      </div>
    </main>
  );
};

export default Page;
